---
- name: apt install kvm packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  vars:
    packages:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager

- name: start enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
