---
- name: Install multi packages
  apt:
    name:
      - qemu-kvm
      - libvirt-bin
      - virtinst
      - bridge-utils
      - libosinfo-bin
      - libguestfs-tools
      - virt-top
      - virt-manager
      - qemu-system
      - libguestfs-tools
      - virt-top
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: start enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
