---
- name: Install multi packages
  apt:
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: start enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
